    ---
    - hosts: all
      tasks:
        - name: install python packages
          pip:
            requirements : terenas/req.txt
            
        - name: ensure nginx is at the latest version
          apt: name=nginx state=latest
          become: yes
          
        - name: start nginx
          service:
              name: nginx
              state: started
              enabled: yes
          become: yes
          
        - name: copy the nginx config file and restart nginx
          copy:
            src: /home/foo/static_site.cfg
            dest: /etc/nginx/sites-available/static_site.cfg
          become: yes
          
        - name: create symlink
          file:
            src: /etc/nginx/sites-available/static_site.cfg
            dest: /etc/nginx/sites-enabled/default
            state: link
          become: yes
          
        - name: restart nginx
          service:
            name: nginx
            state: restarted
          become: yes
          
        - name: copy web app to server
          copy:
            src:  /home/pollux/terenas
            dest: /home/user/  
              
        - name: copy systemd unit to units dir
          copy:
            src:  /home/pollux/test/arthas.service
            dest: /etc/systemd/system/arthas.service
            become: yes
